### PR TITLE
[WIP] Feature/skills

### PR DESCRIPTION
**Pull request by serpient**
# Child of #109
# Things Done
### 2) General clean up of UserProfile component. Extracted independent components into its own folder. 

gif

# How it Works / Basic Drag-Drop Usage
### 1) Query for techstack / create QA object for dynamicFormContainer
 `UserProfile/UserSkills/SkillUpdater.jsx` queries for all techskills in the database, then passes the results into the formation of a QuestionAnswer object. This QA object is then passed to the DynamicFormContainer
### 2) Options are passed to the Skill Question component in DynamicForms
Options are bundled into skill categories on the left `<RenderSkills />` component. Empty drop cells are rendered on the right `<RenderChosenSkills />` component. These components live in `src/components/DynamicForm/QuestionComponents/SkillSetter/SkillSetter`
#### SourceSkillCard is wrapped in a higher order function from React DnD. 
``` 
export default DragSource(ItemTypes.SKILL_CARD, skillSource, collect)(SourceSkillCard);
```
- the itemTypes for this component should have a matching one in the drop target component.  this lets DnD knows that they are compatible to drag/drop from each other. 
- the middle function in DragSource is a `spec` function. Think of these as ways to pass data around from your target/source components. 
- see below for skillSource and collect descriptions
#### SkillSource function is a spec function that has a few builtin methods that you can call
``` 
const skillSource = {
    beginDrag(props) {
        return {
            skillId: props.skill
        }
    },
    endDrag(props, monitor, component) {
        let results = monitor.getDropResult();
        if (results) {
            let { addSkillHandler, position, skill } = results;
            return addSkillHandler(position, skill);
        }
    }
}
```
- this function has a few methods it can call, see [HERE](http://react-dnd.github.io/react-dnd/docs-drag-source.html) for more methods
- in this case, `beginDrag` is called whenever a drag starts (obvious i know). You should return whatever information you want to access during the drag lifecycle. In this case, I'm returning the entire skill object passed in from parent component props.  BTW, these methods all have access to `props` from the parent component calling this component
- `endDrag` is a function that kicks off when the drag is completed. it has references to parent props, monitor, and the component itself.  `monitor.getDropResult()` will get the returned item from the `drop` function (in sourceTarget component), and in this case, if the result is not null (which happens if you drag the card to a non-type-matching area), I pass the results into a function from the parent. in this case, `addSkillHandler(position, skill)` saves the skill object and position into the array stored in parent state. 
### Collection function creates function that is passed to the component
``` 
function collect(connect, monitor) {
    return {
        connectDragSource: connect.dragSource(),
        isDragging: monitor.isDragging()
    }
}
```
- Again, read all about the collect function [HERE](http://react-dnd.github.io/react-dnd/docs-drag-source.html) and its numerous methods
- `connectDragSource: connectDragSource()` is very important as its the function that is called in the component as `this.props.connectDragSource` to wrap around ONE dragSource. 
- `isDragging` is using monitor to check whether the item is currently being dragged. this can be used in the component to add another styling to component className so it looks different while its being dragged. 
### 4) Creation of Droppable Target in `/SkillSetter/RenderChosenSkills.jsx`
- [DOCUMENTATION](http://react-dnd.github.io/react-dnd/docs-drop-target.html)
- wrap your Target component in higher order function, like so
```
export default DropTarget(ItemTypes.SKILL_CARD, skillTarget, collect)(RenderChosenSkills);
```
- connect looks very similar to dragSource, just change method from `dragSource()` to dragConnect`
```
function collect(connect, monitor) {
    return {
        connectDropTarget: connect.dropTarget(),
        isOver: monitor.isOver()
    }
}
```
- spec function, in this case skillTarget has more limited methods. the `drop` function in this case is wrapping positionID, skill object data from dragSource `beginDrag` function by calling `monitor.getItem()`, and also the reference to the parent function of updating skills.  This data is accessible in the `sourceTarget` component , where `endDrag` method is waiting for it. 
```
const skillTarget = {
    drop(props, monitor) {
        return {
            position: props.position,
            skill: monitor.getItem().skillId,
            addSkillHandler: props.addSkillHandler
        }
    }
}
```
### 5) SkillSetter (the parent component) addSkillHandler  fn takes over
1) takes the skill data and position and saves to state
2) parses the IDs from the array
3) pass the array of IDs into the original dynamicForms `onFormChange` function
```
addSkillHandler = (position, object) => {
        let skills = this.state.CHOSEN_SKILL_ELEMENTS;
        if (!this.checkForNoDuplicates(object)) {
            // if there is a duplicate, set existing
            // object position to empty object
            skills[this.findCurrentPositionOf(object)] = {};
        } 
        skills[position] = object;
        this.setState({ CHOSEN_SKILL_ELEMENTS: skills }, () => {
            this.props.onFormChange(this.idParser());
        })
    }
```

# Questions / Things that don't work
### A) Edit Button is currently always showing
Currently, edit buttons are all always showing when the user is able to edit the user profile. This is because i;m using `PopupMenu` component which links the button/modal together. so if i set the edit button to toggle based off mouseEnter and mouseLeave, it will also affect the skill_updater form modal. Aka, the modal visibility will turn off once the mouse leaves the edit button.  Any tips on what else I can do?

### B) Error message doesnt close when clicking outside the window / Success message does not reset.
After successful skill update, the success icon pops up in form. When closing the skillForm and re-opening, the success modal is still there. Response/Error in state needs to be reset to null.
Current Workaround is to set response/error to null after a few seconds. Is it worth it to try another more proper method?
### [FIXED] C) When dragging the skill card to NOT the first empty container, it breaks when you add / update / move the next card. Says its `undefined`.
The problem was that I was checking for empty object with `obj !== { }` which will never be correct. Switched out this conditional with a more reliable method that checks for whether a object exists
 ```Object.prototype.hasOwnProperty.call(obj, key)```  . Integrated this `isNotEmpty(obj)` function into `findCurrentPositionOf` and `idParser` so that even if you only add a skill to not-0 position, it will remove the empty object. 
### D) UserProfile is inconsistent about whether it waits for the query to finish and thus passing in a complete user object into the component. Sometimes it seems the UserProfile component mounts even with empty `props.data` object, which breaks the entire page. 
Current guess is that I need to pull the updated `<Request />` component that currently lives in `sprint/ticketbox`. I will test this again once that branch has merged into `development.`

### CODE REVIEW

**Comment by thinktwice13** [comment]
Just delete it

**Comment by serpient** [comment]
- add marker icon in edit button. so no more text or border
fontawesome

**Comment by serpient** [comment]
add small voyage cards to left bar.
- shows voyage name / team name

**Comment by serpient** [comment]
vertical line between image and info component on ProjectCards

**Comment by serpient** [comment]
the left/right panel of skills should be swappable. 
- pulling from right will make the option disappear on left.
- dragging it out of right will make the option appear on the left under correct category, and remove it from right.

**Comment by serpient** [comment]
- submit button should only be valid if there isn't empty objects between values in the array.
add check to utilities.js file - check for empties between values. 

- also initialize the skill_ids array to  `skill_ids: [null, null, null, null, null]` in DynamicFormContainer.jsx , line 96. keep a variable called MAX_SKILL_CHOICES and put a comment above it that says its a magic number ( a static number that controls everything else ). 

- currently what is rendered and what is in state does not match. this is because we are removing the empty nulls when saving it in state.  try using null instead?

**Comment by serpient** [comment]
Extract the UserSkills Component into its own independent component that can be imported into userProfile / project / applications.

**Comment by serpient** [comment]
- dragging a skill on top of an existing skill should push the existing one down

**Comment by serpient** [comment]
Skills should not be capped
- take out drag/drop, use options dropdown
- let users add/delete it from the form
- level in the skill is controlled by how many projects u have completed with that skill
- completed project skills will automatically be added to user profile skills with +1 in their level
- manually added without project backing should default to 0 for level

Desired_Skills capped to 5

**Comment by serpient** [comment]
Newsfeed
- is per project not team

**Pull request merged**
