### PR TITLE
Ticketbox TeamHelp error fix

### PR DESCRIPTION
**Pull request by thinktwice13**
Adjusted Ticketbox TeamHelp section for new schema

### CODE REVIEW

**Comment by serpient** [comment]
Tested this in development, and submitting a help issue is returning an error
image

**Comment by serpient** [comment]
@the-vampiire  @thinktwice13  fixed text centering -- ready to go!
BTW, if usual methods of centering doesnt work for you guys, try the below in the parent container of the thing you want to center. 
```
display: grid (or flex);
justify-items: center; (horizontal align)
align-items: center; (vertical align)
```

image

**Comment by the-vampiire** [comment]
Awesome thanks wolf. Now when we bring back help requests will this need to be refactored or it will adjust to the third item? 

If the former can you add a todo on the commented out help item and the css that it needs to be updated when we bring HR back

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by serpient** [comment]
when u bring back the third item, it should arrange itself automatically.

**Pull request merged**
